name: Examples
on:
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'run-all-examples'
          reaction: rocket
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        if: steps.check.outputs.triggered == 'true'
        with:
          version: '1'
      - shell: bash
        run: julia --project -e 'import Pkg; Pkg.instantiate(); Pkg.activate("examples"); Pkg.instantiate()'
      - shell: bash
        run: cd examples; julia run_all_examples.jl
